global.env = {
  APP_COLLAB_ENV: `$(APP_COLLAB_ENV)`,
  APP_COLLAB_NAME: `$(APP_COLLAB_NAME)`,
  APP_COLLAB_PORT: `$(APP_COLLAB_PORT)`,
  APP_COLLAB_MONGO_DB: `$(APP_COLLAB_MONGO_DB)`,
  APP_COLLAB_MONGO_HOST: `$(APP_COLLAB_MONGO_HOST)`,
  APP_COLLAB_MONGO_PORT: `$(APP_COLLAB_MONGO_PORT)`,
  APP_COLLAB_MONGO_USER: `$(APP_COLLAB_MONGO_USER)`,
  APP_COLLAB_MONGO_PWD: `$(APP_COLLAB_MONGO_PWD)`,
  APP_COLLAB_MONGO_CONNECTION_STRING: "",
  APP_COLLAB_KEYCLOAK_URL: `$(APP_COLLAB_KEYCLOAK_URL)`,
};
